/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import com.db4o.Db4oEmbedded;
import com.db4o.ObjectContainer;
import com.db4o.ObjectSet;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import modelo.Categoria;
import modelo.Encargado;
import modelo.Ingredientes;
import modelo.Plato;


/**
 *
 * @author Angel
 */
public class Vista extends javax.swing.JFrame {

    private static ArrayList<Encargado> listaencargados = new ArrayList<>();
    private static ArrayList<Categoria> listacategorias = new ArrayList<>();
    private static ArrayList<Plato> listaplatos = new ArrayList<>();
    private static ArrayList<Ingredientes> listaingredientes= new ArrayList<Ingredientes>();
    private static DefaultListModel modeloIngredientes = new DefaultListModel();
    private static DefaultListModel modeloPlatos = new DefaultListModel();
    private static DefaultListModel modeloCategorias = new DefaultListModel();
    
    private static final String urlBD = "restaurante.yap";
    private static ObjectContainer db;
    
    /**
     * Creates new form Vista
     */;
    
    
    /**
     * Creates new form Vista
     */
    public Vista() {
        initComponents();
        cargarBBDD();
        cargarTodosJCombox();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelEncargadoNombre = new javax.swing.JLabel();
        jLabelEncargadoApellidos = new javax.swing.JLabel();
        jTextFieldEncargadoNombre = new javax.swing.JTextField();
        jTextFieldEncargadoApellidos = new javax.swing.JTextField();
        jButtonEncargadoCrear = new javax.swing.JButton();
        jComboBoxEncargados = new javax.swing.JComboBox();
        jButtonEncargadoBorrar = new javax.swing.JButton();
        jButtonEncargadoBuscar = new javax.swing.JButton();
        jLabelCategoriaNombre = new javax.swing.JLabel();
        jTextFieldCategoriaNombre = new javax.swing.JTextField();
        jLabelCategoriaDescripcion = new javax.swing.JLabel();
        jTextFieldCategoriaDescripcion = new javax.swing.JTextField();
        jButtonCategoriaCrear = new javax.swing.JButton();
        jComboBoxCategorias = new javax.swing.JComboBox();
        jButtonCategoriaBorrar = new javax.swing.JButton();
        jButtonCategoriaBuscar = new javax.swing.JButton();
        jLabelPlatoNombre = new javax.swing.JLabel();
        jTextFieldPlatoNombre = new javax.swing.JTextField();
        jLabelPlatoDificultad = new javax.swing.JLabel();
        jComboBoxPlatoDificultad = new javax.swing.JComboBox();
        jLabelPlatoPrecio = new javax.swing.JLabel();
        jTextFieldPlatoPrecio = new javax.swing.JTextField();
        jLabelPlatoDescripcion = new javax.swing.JLabel();
        jTextFieldPlatoDescripcion = new javax.swing.JTextField();
        jButtonPlatoCrear = new javax.swing.JButton();
        jComboBoxPlatos = new javax.swing.JComboBox();
        jButtonBorrarPlato = new javax.swing.JButton();
        jLabelIngredienteNombre = new javax.swing.JLabel();
        jTextFieldIngredienteNombre = new javax.swing.JTextField();
        jButtonIngredienteCrear = new javax.swing.JButton();
        jButtonGuardar = new javax.swing.JButton();
        jButtonImprimirCarta = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabelCategoriaListado = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jListCategorias = new javax.swing.JList();
        jLabelPlatoListado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListPlatos = new javax.swing.JList();
        jLabelIngredientesListado = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListIngredientes = new javax.swing.JList();
        jSeparator2 = new javax.swing.JSeparator();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextAreaImpresion = new javax.swing.JTextArea();
        jButtonModificaEncargado = new javax.swing.JButton();
        jButtonCategoriaModificar = new javax.swing.JButton();
        jButtonPlatoBuscar = new javax.swing.JButton();
        jButtonPlatoModificar = new javax.swing.JButton();
        jButtonCategoriaAgrega = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurante DB40 ");
        setResizable(false);

        jLabelEncargadoNombre.setText("Nombre Encargado");

        jLabelEncargadoApellidos.setText("Apellidos");

        jButtonEncargadoCrear.setText("Crear");
        jButtonEncargadoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncargadoCrearActionPerformed(evt);
            }
        });

        jButtonEncargadoBorrar.setText("Borrar");
        jButtonEncargadoBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncargadoBorrarActionPerformed(evt);
            }
        });

        jButtonEncargadoBuscar.setText("Buscar");
        jButtonEncargadoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEncargadoBuscarActionPerformed(evt);
            }
        });

        jLabelCategoriaNombre.setText("Nombre Categoria");

        jLabelCategoriaDescripcion.setText("Descripcion");

        jButtonCategoriaCrear.setText("Crear");
        jButtonCategoriaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaCrearActionPerformed(evt);
            }
        });

        jButtonCategoriaBorrar.setText("Borrar");
        jButtonCategoriaBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaBorrarActionPerformed(evt);
            }
        });

        jButtonCategoriaBuscar.setText("Buscar");
        jButtonCategoriaBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaBuscarActionPerformed(evt);
            }
        });

        jLabelPlatoNombre.setText("Nombre Plato");

        jLabelPlatoDificultad.setText("Dificultad");

        jComboBoxPlatoDificultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Facil", "Intermedio", "Dificil", "Ferran Adria" }));

        jLabelPlatoPrecio.setText("Precio");

        jTextFieldPlatoPrecio.setText("0");

        jLabelPlatoDescripcion.setText("Descripcion");

        jButtonPlatoCrear.setText("Crear");
        jButtonPlatoCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlatoCrearActionPerformed(evt);
            }
        });

        jButtonBorrarPlato.setText("Borrar");
        jButtonBorrarPlato.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarPlatoActionPerformed(evt);
            }
        });

        jLabelIngredienteNombre.setText("Nombre Ingrediente");

        jTextFieldIngredienteNombre.setToolTipText("");

        jButtonIngredienteCrear.setText("Crear");
        jButtonIngredienteCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIngredienteCrearActionPerformed(evt);
            }
        });

        jButtonGuardar.setText("Guardar en DB40");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jButtonImprimirCarta.setText("Imprimir");
        jButtonImprimirCarta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonImprimirCartaActionPerformed(evt);
            }
        });

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabelCategoriaListado.setText("Listado Categorias");

        jScrollPane3.setViewportView(jListCategorias);

        jLabelPlatoListado.setText("Listado Platos");

        jScrollPane2.setViewportView(jListPlatos);

        jLabelIngredientesListado.setText("Listado Ingredientes");

        jScrollPane1.setViewportView(jListIngredientes);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jTextAreaImpresion.setColumns(20);
        jTextAreaImpresion.setRows(5);
        jScrollPane5.setViewportView(jTextAreaImpresion);

        jButtonModificaEncargado.setText("Modificar");
        jButtonModificaEncargado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModificaEncargadoActionPerformed(evt);
            }
        });

        jButtonCategoriaModificar.setText("Modificar");
        jButtonCategoriaModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaModificarActionPerformed(evt);
            }
        });

        jButtonPlatoBuscar.setText("Buscar");
        jButtonPlatoBuscar.setToolTipText("");
        jButtonPlatoBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlatoBuscarActionPerformed(evt);
            }
        });

        jButtonPlatoModificar.setText("Modificar");
        jButtonPlatoModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlatoModificarActionPerformed(evt);
            }
        });

        jButtonCategoriaAgrega.setText("Agrega");
        jButtonCategoriaAgrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCategoriaAgregaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelCategoriaNombre)
                                            .addComponent(jLabelCategoriaDescripcion))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldCategoriaDescripcion)
                                            .addComponent(jTextFieldCategoriaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jComboBoxCategorias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCategoriaModificar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jButtonCategoriaCrear))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jButtonCategoriaBuscar)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jButtonCategoriaBorrar))
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(jLabelEncargadoNombre)
                                                                    .addComponent(jLabelEncargadoApellidos))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                    .addComponent(jTextFieldEncargadoNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                                                    .addComponent(jTextFieldEncargadoApellidos)))
                                                            .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jButtonModificaEncargado)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jButtonEncargadoCrear)))
                                                        .addComponent(jComboBoxEncargados, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                                    .addGroup(layout.createSequentialGroup()
                                                        .addComponent(jButtonEncargadoBuscar)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(jButtonEncargadoBorrar)))
                                                .addGroup(layout.createSequentialGroup()
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabelPlatoNombre)
                                                        .addComponent(jLabelPlatoDificultad))
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                        .addComponent(jComboBoxPlatoDificultad, 0, 200, Short.MAX_VALUE)
                                                        .addComponent(jTextFieldPlatoNombre)))
                                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                                    .addGap(171, 171, 171)
                                                    .addComponent(jButtonPlatoModificar)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jButtonPlatoCrear)))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelPlatoPrecio)
                                            .addComponent(jLabelPlatoDescripcion))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFieldPlatoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                            .addComponent(jTextFieldPlatoDescripcion))))
                                .addGap(75, 75, 75))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jComboBoxPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonPlatoBuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonBorrarPlato)
                        .addGap(77, 77, 77)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelIngredienteNombre)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldIngredienteNombre)
                        .addGap(24, 24, 24))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButtonIngredienteCrear))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabelCategoriaListado)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonCategoriaAgrega))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                .addComponent(jScrollPane2)
                                .addComponent(jLabelPlatoListado)
                                .addComponent(jScrollPane3))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelIngredientesListado)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonGuardar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonImprimirCarta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)))
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(91, 91, 91))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoriaListado)
                            .addComponent(jButtonCategoriaAgrega))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabelPlatoListado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelIngredientesListado)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButtonGuardar)
                                .addComponent(jButtonImprimirCarta)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelIngredienteNombre)
                            .addComponent(jTextFieldIngredienteNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonIngredienteCrear))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEncargadoNombre)
                            .addComponent(jTextFieldEncargadoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelEncargadoApellidos)
                            .addComponent(jTextFieldEncargadoApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEncargadoCrear)
                            .addComponent(jButtonModificaEncargado))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxEncargados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonEncargadoBorrar)
                            .addComponent(jButtonEncargadoBuscar))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoriaNombre)
                            .addComponent(jTextFieldCategoriaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCategoriaDescripcion)
                            .addComponent(jTextFieldCategoriaDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCategoriaCrear)
                            .addComponent(jButtonCategoriaModificar))
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonCategoriaBorrar)
                            .addComponent(jButtonCategoriaBuscar))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlatoNombre)
                            .addComponent(jTextFieldPlatoNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlatoDificultad)
                            .addComponent(jComboBoxPlatoDificultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlatoPrecio)
                            .addComponent(jTextFieldPlatoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldPlatoDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelPlatoDescripcion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPlatoModificar)
                            .addComponent(jButtonPlatoCrear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxPlatos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonPlatoBuscar)
                            .addComponent(jButtonBorrarPlato))))
                .addGap(85, 166, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 757, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane5)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIngredienteCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIngredienteCrearActionPerformed
        Ingredientes ingr = new Ingredientes(jTextFieldIngredienteNombre.getText());
        listaingredientes.add(ingr); 
        cargarJlistIngredientes();
        
    }//GEN-LAST:event_jButtonIngredienteCrearActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
       guardarBBDD();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonEncargadoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncargadoCrearActionPerformed
        ArrayList<Categoria> miscategorias = new ArrayList<>();        
        Iterator itJlistCategorias = jListCategorias.getSelectedValuesList().iterator();
        int numCategoriaSelect = jListCategorias.getSelectedValuesList().size();
        String[] arrayCategSelect = new String[numCategoriaSelect];
        for (int i=0; i < numCategoriaSelect; i++){
            arrayCategSelect[i] = itJlistCategorias.next().toString();
        }
        Iterator itListaCategorias = listacategorias.iterator();

        while (itListaCategorias.hasNext()){
            Categoria ctg = (Categoria) itListaCategorias.next();
            for (int i= 0; i < numCategoriaSelect; i++){
                if (ctg.getNombreCategoria().equals(arrayCategSelect[i])){
                    miscategorias.add(ctg);
                }
            }
        }

        Encargado encargado = new Encargado(jTextFieldEncargadoNombre.getText(),
            jTextFieldEncargadoApellidos.getText());
        encargado.setListaCategoria(miscategorias);
        Iterator prueba = encargado.getListaCategoria().iterator();
        while (prueba.hasNext()){
            Categoria categ = (Categoria) prueba.next();
            System.out.println(categ.getNombreCategoria());
        }
        listaencargados.add(encargado);
        cargarJcomboBoxEncargados();
        guardarBBDD();

    }//GEN-LAST:event_jButtonEncargadoCrearActionPerformed

    private void jButtonPlatoCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlatoCrearActionPerformed
        ArrayList<Ingredientes> misIngredientes = new ArrayList<>();
        Iterator itJlistIngredientes = jListIngredientes.getSelectedValuesList().iterator();         
        int numingrSelect = jListIngredientes.getSelectedValuesList().size();
        String[] arrayIngr = new String[numingrSelect];
        for (int i = 0 ; i < numingrSelect; i++) {
         arrayIngr[i] = itJlistIngredientes.next().toString();
         
        }        
        Iterator itlistadoIngredientes = listaingredientes.iterator();        
        while (itlistadoIngredientes.hasNext()){
            Ingredientes ingr = (Ingredientes) itlistadoIngredientes.next();
            for (int i = 0; i < numingrSelect; i++){
                if (ingr.getNombreIngrediente().equals(arrayIngr[i])){
                   misIngredientes.add(ingr); 
                }
            }
        }
        Plato plato= new Plato(jTextFieldPlatoNombre.getText(),
            jTextFieldPlatoDescripcion.getText(),
            jComboBoxPlatoDificultad.getSelectedItem().toString(),
            Float.valueOf(jTextFieldPlatoPrecio.getText()));
        plato.setListaIngredientes(misIngredientes);
        listaplatos.add(plato);   
        cargarJcomboboxPlatos();
        cargarJListPlatos();

    }//GEN-LAST:event_jButtonPlatoCrearActionPerformed

    private void jButtonCategoriaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaCrearActionPerformed
        ArrayList<Plato> misplatos = new ArrayList<>();
        Iterator itJlistPlatos = jListPlatos.getSelectedValuesList().iterator();
        int numPlatosSelect = jListPlatos.getSelectedValuesList().size();
        String[] arrayNumPlatosSelec = new String[numPlatosSelect];
        for (int i= 0; i < numPlatosSelect; i++){
            arrayNumPlatosSelec[i] = itJlistPlatos.next().toString();
        }
                
        Iterator itListadosPlatos = listaplatos.iterator();

        while (itListadosPlatos.hasNext()){
            Plato plato = (Plato) itListadosPlatos.next();
            for (int i=0; i< numPlatosSelect; i++){
                if (plato.getNombrePlato().equals(arrayNumPlatosSelec[i])){
                    misplatos.add(plato);
                }
            }
        }

        Categoria categoria = new Categoria(jTextFieldCategoriaNombre.getText(),
            jTextFieldCategoriaDescripcion.getText());

        categoria.setListaPlatos(misplatos);
        
        listacategorias.add(categoria);

        cargarJcomboBoxCategorias();
        cargarJListCategorias();

    }//GEN-LAST:event_jButtonCategoriaCrearActionPerformed

    private void jButtonImprimirCartaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonImprimirCartaActionPerformed
       imprimirtodo();
    }//GEN-LAST:event_jButtonImprimirCartaActionPerformed

    private void jButtonEncargadoBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncargadoBorrarActionPerformed
        String nombreEncargado = jComboBoxEncargados.getSelectedItem().toString();
        for (Encargado encar : listaencargados) {
            if (encar.getNombreEncargado().equals(nombreEncargado)){
                listaencargados.remove(encar);
            }            
        }
        guardarBBDD();
        cargarJcomboBoxEncargados();
    }//GEN-LAST:event_jButtonEncargadoBorrarActionPerformed

    private void jButtonEncargadoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEncargadoBuscarActionPerformed
        String nombreEncargado = jComboBoxEncargados.getSelectedItem().toString();
        for (Encargado encar : listaencargados) {
            if (encar.getNombreEncargado().equals(nombreEncargado)){
                jTextFieldEncargadoNombre.setText(encar.getNombreEncargado());
                jTextFieldEncargadoApellidos.setText(encar.getApellidos());
            }            
        }
    }//GEN-LAST:event_jButtonEncargadoBuscarActionPerformed

    private void jButtonModificaEncargadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModificaEncargadoActionPerformed
        String nombreNuevo, apellidos;
        nombreNuevo = jTextFieldEncargadoNombre.getText();
        apellidos = jTextFieldEncargadoApellidos.getText();
        String nombreEncargado = jComboBoxEncargados.getSelectedItem().toString();
        for (Encargado encar : listaencargados) {
            if (encar.getNombreEncargado().equals(nombreEncargado)){
                encar.setNombreEncargado(nombreNuevo);
                encar.setApellidos(apellidos);
                break;
            }            
        }
        
        cargarJcomboBoxEncargados();
        guardarBBDD();
    }//GEN-LAST:event_jButtonModificaEncargadoActionPerformed

    private void jButtonCategoriaBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaBuscarActionPerformed
        String nombreCategoria = jComboBoxCategorias.getSelectedItem().toString();
        Iterator itcategorias = listacategorias.iterator();
        while (itcategorias.hasNext()){
            Categoria ctg = (Categoria) itcategorias.next();
            if (ctg.getNombreCategoria().equals(nombreCategoria)){
                jTextFieldCategoriaNombre.setText(ctg.getNombreCategoria());
                jTextFieldCategoriaDescripcion.setText(ctg.getDescripcionCategioria());
            }
        }
        
    }//GEN-LAST:event_jButtonCategoriaBuscarActionPerformed

    private void jButtonCategoriaBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaBorrarActionPerformed
        String nombreCategoria = jComboBoxCategorias.getSelectedItem().toString();
        
        Iterator itencar = listaencargados.iterator();
        Iterator itcategoria = listacategorias.iterator();
        
        
        while (itencar.hasNext()){
            Encargado encargado = (Encargado) itencar.next();
           
            Iterator itctg = encargado.getListaCategoria().iterator();
            while (itctg.hasNext()){
                Categoria ctg = (Categoria) itctg.next();
                if (ctg.getNombreCategoria().equals(nombreCategoria)){
                    encargado.getListaCategoria().remove(ctg);
                }
            }
        }
        
        while (itcategoria.hasNext()){
            Categoria categoria = (Categoria) itcategoria.next();
            if (categoria.getNombreCategoria().equals(nombreCategoria)){
                listacategorias.remove(categoria);
            }
        }
        
        cargarJcomboBoxCategorias();
        cargarJListCategorias();
        guardarBBDD();
    }//GEN-LAST:event_jButtonCategoriaBorrarActionPerformed

    private void jButtonCategoriaModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaModificarActionPerformed
        String nombreCategoria = jComboBoxCategorias.getSelectedItem().toString();
        String nuevoNombreCategoria, descripcion;
        nuevoNombreCategoria = jTextFieldCategoriaNombre.getText();
        descripcion = jTextFieldCategoriaDescripcion.getText();
        

        
        Iterator itencar = listaencargados.iterator();
        Iterator itcategoria = listacategorias.iterator();
        
        
        while (itencar.hasNext()){
            Encargado encargado = (Encargado) itencar.next();
           
            Iterator itctg = encargado.getListaCategoria().iterator();
            while (itctg.hasNext()){
                Categoria ctg = (Categoria) itctg.next();
                if (ctg.getNombreCategoria().equals(nombreCategoria)){
                    encargado.getListaCategoria().remove(ctg);
                    ctg.setNombreCategoria(nuevoNombreCategoria);
                    ctg.setDescripcionCategioria(descripcion);
                    encargado.getListaCategoria().add(ctg);
                }
            }
        }
        
        while (itcategoria.hasNext()){
            Categoria categoria = (Categoria) itcategoria.next();
            if (categoria.getNombreCategoria().equals(nombreCategoria)){
               listacategorias.remove(categoria);
               categoria.setNombreCategoria(nuevoNombreCategoria);
               categoria.setDescripcionCategioria(descripcion);
               listacategorias.add(categoria);
            }
        }
        
        cargarJcomboBoxCategorias();
        cargarJListCategorias();
        guardarBBDD();
    }//GEN-LAST:event_jButtonCategoriaModificarActionPerformed

    private void jButtonBorrarPlatoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarPlatoActionPerformed
        String nombreplato = jComboBoxPlatos.getSelectedItem().toString();
        
        Iterator itencargados = listaencargados.iterator();
        
        Plato plato = new Plato();
        while (itencargados.hasNext()){
            Encargado encar = (Encargado) itencargados.next();
            Iterator itcategoria = encar.getListaCategoria().iterator();
            while(itcategoria.hasNext()){
                Categoria categ = (Categoria) itcategoria.next();
                Iterator itplt = categ.getListaPlatos().iterator();
                while (itplt.hasNext()){
                    plato = (Plato) itplt.next();
                    if (plato.getNombrePlato().equals(nombreplato)){
                        categ.getListaPlatos().remove(plato);
                    }
                }
            }
            
        listaplatos.remove(plato);
        }
        
        cargarJcomboboxPlatos();
        cargarJListPlatos();
        guardarBBDD();
        
        
    }//GEN-LAST:event_jButtonBorrarPlatoActionPerformed

    private void jButtonPlatoBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlatoBuscarActionPerformed
        String nombreplato = jComboBoxPlatos.getSelectedItem().toString();
        Iterator itplatos = listaplatos.iterator();
        
        while (itplatos.hasNext()){
            Plato plato = (Plato) itplatos.next();
            if (plato.getNombrePlato().equals(nombreplato)){
                jTextFieldPlatoNombre.setText(plato.getNombrePlato());
                jTextFieldPlatoDescripcion.setText(plato.getDescripcionPlato());
                jTextFieldPlatoPrecio.setText(plato.getPrecio().toString());
                jComboBoxPlatoDificultad.setSelectedItem(plato.getNivelDificultad());
                break;
            }
            
            
        }
    }//GEN-LAST:event_jButtonPlatoBuscarActionPerformed

    private void jButtonPlatoModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlatoModificarActionPerformed
        String nombreplato = jComboBoxPlatos.getSelectedItem().toString();
        String nuevoNombrePlato, descripcion, dificultad;
        Float precio;
        
        nuevoNombrePlato = jTextFieldPlatoNombre.getText();
        descripcion = jTextFieldPlatoDescripcion.getText();
        dificultad = jComboBoxPlatoDificultad.getSelectedItem().toString();
        precio = Float.valueOf(jTextFieldPlatoPrecio.getText());
        
        Iterator itencargados = listaencargados.iterator();
        Iterator itplatos = listaplatos.iterator();
        
        
        while (itencargados.hasNext()){
            Encargado encar = (Encargado) itencargados.next();
            Iterator itcategoria = encar.getListaCategoria().iterator();
            while(itcategoria.hasNext()){
                Categoria categ = (Categoria) itcategoria.next();
                Iterator itplt = categ.getListaPlatos().iterator();
                while (itplt.hasNext()){
                   Plato plato = (Plato) itplt.next();
                    if (plato.getNombrePlato().equals(nombreplato)){
                        categ.getListaPlatos().remove(plato);
                        plato.setNombrePlato(nuevoNombrePlato);
                        plato.setDescripcionPlato(descripcion);
                        plato.setNivelDificultad(dificultad);
                        plato.setPrecio(precio);
                        categ.getListaPlatos().add(plato);
                    }
                }
            }
        
        while (itplatos.hasNext()){
            Plato plato = (Plato) itplatos.next();
            if (plato.getNombrePlato().equals(nombreplato)){
                listaplatos.remove(plato);
                plato.setNombrePlato(nuevoNombrePlato);
                plato.setDescripcionPlato(descripcion);
                plato.setNivelDificultad(dificultad);
                plato.setPrecio(precio);
                listaplatos.add(plato);
            }
        }
        
        }
        
        cargarJcomboboxPlatos();
        cargarJListPlatos();
        guardarBBDD();
    }//GEN-LAST:event_jButtonPlatoModificarActionPerformed

    private void jButtonCategoriaAgregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCategoriaAgregaActionPerformed
        Iterator itjlistcategoria = jListCategorias.getSelectedValuesList().iterator();
        int numcategoriasSelect = jListCategorias.getSelectedValuesList().size();
        String[] arrayCategorias = new String[numcategoriasSelect];
        for (int i = 0 ; i < numcategoriasSelect; i++){
            arrayCategorias[i] = itjlistcategoria.next().toString();
        }
        
        String nombreEncargado = jComboBoxEncargados.getSelectedItem().toString();
        
        
        
        Iterator itencargados = listaencargados.iterator();
        while (itencargados.hasNext()){
            Encargado a = (Encargado) itencargados.next();
            if (a.getNombreEncargado().equals(nombreEncargado)){
                Iterator itcategorias = listacategorias.iterator();
                while (itcategorias.hasNext()){
                    Categoria categoria = (Categoria) itcategorias.next();
                    for (int i =0; i < numcategoriasSelect; i++){
                        if (categoria.getNombreCategoria().equals(arrayCategorias[i])){
                            a.getListaCategoria().add(categoria);
                        }
                    }
                }
                
            }
        }
        
        guardarBBDD();
        
    }//GEN-LAST:event_jButtonCategoriaAgregaActionPerformed

    private static void cargarBBDD(){
        db = Db4oEmbedded.openFile(urlBD);
        Encargado a = new Encargado();
        ObjectSet<Encargado> resultadoConsulta = db.queryByExample(a);
        System.out.println(resultadoConsulta.size());
        if (resultadoConsulta.size() == 0){
        
        }
        else{
           while (resultadoConsulta.hasNext()){
               Encargado b = (Encargado) resultadoConsulta.next();
               listaencargados.add(b);
           }
        }
        db.close();
        
    }
    
    private static void cargarTodosJCombox(){
        Iterator itEncargados = listaencargados.iterator();
        while (itEncargados.hasNext()){
            Encargado encargado = (Encargado) itEncargados.next();
            Iterator itcategoria = encargado.getListaCategoria().iterator();
            while (itcategoria.hasNext()){
                Categoria categoria = (Categoria) itcategoria.next();
                listacategorias.add(categoria);
                Iterator itplatos = categoria.getListaPlatos().iterator();
                while (itplatos.hasNext()){
                    Plato plato = (Plato) itplatos.next();
                    listaplatos.add(plato);
                }
            }
        }
        cargarJcomboBoxEncargados();
        cargarJcomboBoxCategorias();
        cargarJcomboboxPlatos();
        cargarJListCategorias();
        cargarJListPlatos();
    }
    
    private static void cargarJcomboBoxEncargados(){
       Iterator itEncargados = listaencargados.iterator();
       jComboBoxEncargados.removeAllItems();
       while (itEncargados.hasNext()){
           Encargado encargado = (Encargado) itEncargados.next();
           jComboBoxEncargados.addItem(encargado.getNombreEncargado());
       }
    }
    
    private static void cargarJcomboBoxCategorias(){
        Iterator itCategorias = listacategorias.iterator();
        jComboBoxCategorias.removeAllItems();
        while (itCategorias.hasNext()){
            Categoria catg = (Categoria) itCategorias.next();
            jComboBoxCategorias.addItem(catg.getNombreCategoria());
        }
    }
    
    private static void cargarJcomboboxPlatos(){
        Iterator itplatos = listaplatos.iterator();
        jComboBoxPlatos.removeAllItems();
        while (itplatos.hasNext()){
            Plato plato = (Plato) itplatos.next();
            jComboBoxPlatos.addItem(plato.getNombrePlato());
        }
    }
    
    private static void cargarJlistIngredientes(){
        Iterator it = listaingredientes.iterator();
        modeloIngredientes.clear();
        while (it.hasNext()){
            Ingredientes ingr = (Ingredientes) it.next();
            modeloIngredientes.addElement(ingr.getNombreIngrediente());
        }
        jListIngredientes.setModel(modeloIngredientes);
    }
    
    private static void cargarJListPlatos(){
        Iterator it = listaplatos.iterator();
        modeloPlatos.clear();
        while(it.hasNext()){
            Plato plato = (Plato) it.next();
            modeloPlatos.addElement(plato.getNombrePlato());
        }
        jListPlatos.setModel(modeloPlatos);
    }
    
    private static void cargarJListCategorias(){
        Iterator it = listacategorias.iterator();
        modeloCategorias.clear();
        while (it.hasNext()){
            Categoria ctg = (Categoria) it.next();
            modeloCategorias.addElement(ctg.getNombreCategoria());
        }
        jListCategorias.setModel(modeloCategorias);
    }
    
    private void guardarBBDD(){
        File mifichero = new File(urlBD);        
        if (mifichero.exists()){
            mifichero.delete();            
        }
        db = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), urlBD);
        db.store(listaencargados);
        db.close();
    }
    
    private void imprimirtodo(){
        String carta = "";
        Iterator itEncargados = listaencargados.iterator();
        while (itEncargados.hasNext()){
            Encargado encargado = (Encargado) itEncargados.next();
            carta += "Nombre Encargado: " + encargado.getNombreEncargado() + " \n";
            carta += "Apellidos: " + encargado.getApellidos() + " \n";
            Iterator itCategorias = encargado.getListaCategoria().iterator();
            while (itCategorias.hasNext()){
                Categoria categoria = (Categoria) itCategorias.next();
                carta += "      Categoria: " + categoria.getNombreCategoria() + " \n" ;
                carta += "      Descripcion: " + categoria.getDescripcionCategioria() + " \n";
                Iterator itPlatos = categoria.getListaPlatos().iterator();
                while (itPlatos.hasNext()){
                    Plato plato = (Plato) itPlatos.next();
                    carta += "            Nombre plato: " + plato.getNombrePlato() + " \n";
                    carta += "            Descripcion: " + plato.getDescripcionPlato() + " \n";
                    carta += "            Dificultad: " + plato.getNivelDificultad() + " \n";
                    carta += "            Precio: " + plato.getPrecio() + " \n";
                    Iterator itIngredientes = plato.getListaIngredientes().iterator();
                    while (itIngredientes.hasNext()){
                        Ingredientes ingrediente = (Ingredientes) itIngredientes.next();
                        carta +="                  Ingrediente: " + ingrediente.getNombreIngrediente() + " \n";
                    }
                }
            }
        }
        
        jTextAreaImpresion.setText(carta);
        
    }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrarPlato;
    private javax.swing.JButton jButtonCategoriaAgrega;
    private javax.swing.JButton jButtonCategoriaBorrar;
    private javax.swing.JButton jButtonCategoriaBuscar;
    private javax.swing.JButton jButtonCategoriaCrear;
    private javax.swing.JButton jButtonCategoriaModificar;
    private javax.swing.JButton jButtonEncargadoBorrar;
    private javax.swing.JButton jButtonEncargadoBuscar;
    private javax.swing.JButton jButtonEncargadoCrear;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonImprimirCarta;
    private javax.swing.JButton jButtonIngredienteCrear;
    private javax.swing.JButton jButtonModificaEncargado;
    private javax.swing.JButton jButtonPlatoBuscar;
    private javax.swing.JButton jButtonPlatoCrear;
    private javax.swing.JButton jButtonPlatoModificar;
    private static javax.swing.JComboBox jComboBoxCategorias;
    private static javax.swing.JComboBox jComboBoxEncargados;
    private javax.swing.JComboBox jComboBoxPlatoDificultad;
    private static javax.swing.JComboBox jComboBoxPlatos;
    private javax.swing.JLabel jLabelCategoriaDescripcion;
    private javax.swing.JLabel jLabelCategoriaListado;
    private javax.swing.JLabel jLabelCategoriaNombre;
    private javax.swing.JLabel jLabelEncargadoApellidos;
    private javax.swing.JLabel jLabelEncargadoNombre;
    private javax.swing.JLabel jLabelIngredienteNombre;
    private javax.swing.JLabel jLabelIngredientesListado;
    private javax.swing.JLabel jLabelPlatoDescripcion;
    private javax.swing.JLabel jLabelPlatoDificultad;
    private javax.swing.JLabel jLabelPlatoListado;
    private javax.swing.JLabel jLabelPlatoNombre;
    private javax.swing.JLabel jLabelPlatoPrecio;
    private static javax.swing.JList jListCategorias;
    private static javax.swing.JList jListIngredientes;
    private static javax.swing.JList jListPlatos;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaImpresion;
    private javax.swing.JTextField jTextFieldCategoriaDescripcion;
    private javax.swing.JTextField jTextFieldCategoriaNombre;
    private javax.swing.JTextField jTextFieldEncargadoApellidos;
    private javax.swing.JTextField jTextFieldEncargadoNombre;
    private javax.swing.JTextField jTextFieldIngredienteNombre;
    private javax.swing.JTextField jTextFieldPlatoDescripcion;
    private javax.swing.JTextField jTextFieldPlatoNombre;
    private javax.swing.JTextField jTextFieldPlatoPrecio;
    // End of variables declaration//GEN-END:variables
}
